[package]
name = "isqrt"
version = "0.1.0"
authors = ["David S. Smith <david.smith@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.1"
rand_distr = "0.4.0"
